# Generated by Django 5.0.1 on 2024-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_age_remove_customuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(default='', max_length=30),
        ),
    ]
