# Generated by Django 5.0.1 on 2024-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_id',
        ),
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
