# Generated by Django 5.0.1 on 2024-06-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contests', '0002_remove_contest_contest_id_alter_contest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_past_contest',
        ),
        migrations.AlterField(
            model_name='contest',
            name='length',
            field=models.DurationField(),
        ),
    ]
